#runtime: nodejs14
#
#instance_class: B8
#manual_scaling:
#  instances: 1

#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 10

#-url: /favicon.ico
#  static_files: public/favicon.ico
#  upload: public/favicon.ico

#automatic_scaling:
#  max_instances: 1
#  min_instances: 1
#  max_concurrent_requests: 80
#  target_cpu_utilization: 0.95
#  target_throughput_utilization: 0.95
#  max_pending_latency: 15s