runtime: nodejs14
#
#manual_scaling:
#  instances: 1
#  max_pending_latency: 15s

automatic_scaling:
  max_instances: 1
  min_instances: 1
  max_concurrent_requests: 80
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_pending_latency: 15s